### ISSUE TITLE
Broken Twitter Link (hhttps)

### ISSUE THREAD

**Issue by t5r7** [Gum-Joe/tube-world-cup#1]
Twitter link here doesn't work since https has two Hs
https://github.com/Gum-Joe/tube-world-cup/blob/7fc28cb0e1a52fe7403263d0a7681a1a6609b642/src/App.tsx#L333

**Comment by ksambhi** [comment]
Thanks for filing an issue!
I've fixed it with the latest deployment agter noticing this issue, will close this issue once the commit with the fix is pushed.

**Comment by t5r7** [comment]
👍🏻

________________________________
